---
- name: create grub2 block
  blockinfile:
    marker: ""
    content: |
      if [ ${net_default_mac} == {{ mac }} ]; then
      default=0
      fallback=1
      timeout=1
      menuentry "CentOS 8" {
         echo "Loading kernel"
         linux "images/pxeboot/vmlinuz" ip=dhcp console=tty0 console=ttyS0 console=hvc0,115200n8 rd.neednet=1 inst.repo=http://uk.mirrors.clouvider.net/CentOS/8/BaseOS/x86_64/os/ inst.ks=http://192.168.9.2/kickstart/kickstart.cfg
         echo "Loading initrd"
         initrd  "images/pxeboot/initrd.img" 
      }
      fi
    dest: /var/lib/tftpboot/boot/grub2/grub.cfg
  notify:
  - restart tftp
