---
- block:
    - assert:
        that: "{{ helper.networkifacename is defined }}"
    - set_fact:
        networkifacename: "{{ helper.networkifacename }}"
  rescue:
    - set_fact:
        networkifacename: "{{ ansible_default_ipv4.interface }}"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - haproxy
        - httpd
        - vim
        - bash-completion
        - libselinux-python
        - podman
        - nfs-utils
        - syslinux

  - set_fact:
      dhcppkgs:
        - dhcp
        - tftp-server

  - set_fact:
      services:
        - named
        - haproxy
        - httpd
        - rpcbind
  when: ansible_distribution_major_version == "7"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - haproxy
        - httpd
        - vim
        - bash-completion
        - python3-libselinux
        - podman
        - nfs-utils
        - syslinux

  - set_fact:
      dhcppkgs:
        - dhcp-server
        - tftp-server

  - set_fact:
      services:
        - named
        - haproxy
        - httpd
        - rpcbind
  when: ansible_distribution_major_version == "8"
